# HOME ASSISTANT
homeassistant:
  external_url: https://REDACTED
  internal_url: https://REDACTED
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Oslo
  currency: NOK
  packages: !include_dir_named include
  customize_domain:
    automation:
      initial_state: true
  allowlist_external_dirs:
    - /config
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - REDACTED
        - REDACTED
      trusted_users:
        REDACTED: !secret ha_user_id

  customize:
    sensor.matavfall:
      friendly_name: food
    sensor.papir:
      friendly_name: paper
    sensor.restavfall:
      friendly_name: residual
    sensor.nordpool_hvfoss:
      unit_of_measurement: NOK


default_config:


# FRONT-END
frontend: !include themes.yaml
template: !include sidebar.yaml


# LOVELACE
lovelace:
  mode: storage
  dashboards:
    lovelace-homekitesq:
      mode: yaml
      title: Homekitesq
      icon: mdi:view-dashboard-variant
      show_in_sidebar: true
      filename: lovelace-homekitesq.yaml


# HTTP
http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem
  login_attempts_threshold: -1 #5
  ip_ban_enabled: false


# DATABASE
recorder:
  db_url: !secret recorder_db_url
  commit_interval: 30
  exclude:
    entity_globs:
      - sensor.browser_*


# LOGGING
logger:
  default: warning #notset
  logs:
    homeassistant.core: fatal
    homeassistant.components.mqtt: warning
    homeassistant.components.http: warning
    homeassistant.components.websocket_api: fatal
    homeassistant.components.bluetooth_tracker.device_tracker: fatal


# TRACES
trace:
    stored_traces: 10


# INFLUXDB
influxdb:
  host: !secret influx_hst
  port: !secret influx_prt
  database: !secret influx_db
  username: !secret influx_usr
  password: !secret influx_pwd
  precision: s
  max_retries: 3
  default_measurement: state


# INCLUDES
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors/base/
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
group: !include groups/groups.yaml
light: !include groups/lights.yaml
media_player: !include groups/media_players.yaml


# TEXT TO SPEECH
tts:
  - platform: google_translate


# LOCK
lock:
  - platform: template
    name: PC
    value_template: >
      {{ states('input_boolean.computer_lock') }}
    lock:
      service: input_boolean.turn_on
      entity_id: input_boolean.computer_lock
    unlock:
      service: input_boolean.turn_off
      entity_id: input_boolean.computer_lock


# NOTIFY
notify: 
  name: "SAGASDESKTOP"
  platform: hass_agent_notifier
  resource: http://REDACTED


# PYTHON
python_script:


# CAMERA
camera:
  - platform: local_file
    name: driveway_snapshot
    file_path: /config/www/images/cameras/driveway.jpg
  - platform: local_file
    name: doorbell_snapshot
    file_path: /config/www/images/cameras/doorbell.jpg
  - platform: local_file
    name: living_room_snapshot
    file_path: /config/www/images/cameras/living_room.jpg
  - platform: local_file
    name: terrace_snapshot
    file_path: /config/www/images/cameras/terrace.jpg
    

# MIN RENOVASJON
min_renovasjon:
  street_name: "REDACTED"
  house_no: "REDACTED"
  street_code: "REDACTED"
  county_id: "REDACTED"


# MQTT
mqtt:
  sensor:
    # PERSON PERSISTENCE
    - name: "andre_last_changed"
      state_topic: "homeassistant/persistence/andre"
      value_template: "{{ value | replace(' ', 'T') }}"

    - name: "siri_last_changed"
      state_topic: "homeassistant/persistence/siri"
      value_template: "{{ value | replace(' ', 'T') }}"


# WEATHER
weather:
  - platform: pirateweather
    api_key: REDACTED
    # Additional optional values:
    latitude: "REDACTED"
    longitude: "REDACTED"
    mode: daily
    name: pirateweather
    
