# HOME ASSISTANT
homeassistant:
  external_url: https://REDACTED
  internal_url: https://REDACTED
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Oslo
  currency: NOK
  packages: !include_dir_named include
  customize_domain:
    automation:
      initial_state: true
  allowlist_external_dirs:
    - /config
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - REDACTED
        - REDACTED
      trusted_users:
        REDACTED
        REDACTED
        REDACTED
  customize:
    sensor.matavfall:
      friendly_name: food
    sensor.papir:
      friendly_name: paper
    sensor.restavfall:
      friendly_name: residual


default_config:


# FRONT-END
frontend: !include themes.yaml
template: !include sidebar.yaml


# LOVELACE
lovelace:
  mode: storage
  dashboards:
    lovelace-homekitesq:
      mode: yaml
      title: Homekitesq
      icon: mdi:view-dashboard-variant
      show_in_sidebar: true
      filename: lovelace-homekitesq.yaml


# HTTP
http:
  ssl_certificate: REDACTED
  ssl_key: REDACTED
  login_attempts_threshold: -1 #5
  ip_ban_enabled: false


# DATABASE
recorder:
  db_url: !secret recorder_db_url
  commit_interval: 30
  exclude:
    entity_globs:
      - sensor.browser_*


# LOGGING
logger:
  default: warning
  logs:
    homeassistant.core: fatal
    homeassistant.components.mqtt: warning
    homeassistant.components.http: warning
    homeassistant.components.websocket_api: fatal
    homeassistant.components.bluetooth_tracker.device_tracker: fatal


# TRACES
trace:
    stored_traces: 10


# INFLUXDB
influxdb:
  host: !secret influx_hst
  port: !secret influx_prt
  database: !secret influx_db
  username: !secret influx_usr
  password: !secret influx_pwd
  precision: s
  max_retries: 3
  default_measurement: state


# INCLUDES
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors/base/
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
group: !include groups/groups.yaml
light: !include groups/lights.yaml
media_player: !include groups/media_players.yaml


# TEXT TO SPEECH
tts:
  - platform: google_translate


# BrowserMod
browser_mod:
  prefix: browser_


# LOCK
lock:
  - platform: template
    name: PC
    value_template: >
      {{ states('input_boolean.computer_lock') }}
    lock:
      service: input_boolean.turn_on
      entity_id: input_boolean.computer_lock
    unlock:
      service: input_boolean.turn_off
      entity_id: input_boolean.computer_lock


# NOTIFY
notify: 
  name: REDACTED
  platform: hass_agent_notifier
  resource: REDACTED


# PYTHON
python_script:


# MIN RENOVASJON
min_renovasjon:
  street_name: REDACTED
  house_no: REDACTED
  street_code: REDACTED
  county_id: REDACTED


# WEATHER
weather:
  - platform: pirateweather
    api_key: REDACTED
    latitude: "REDACTED"
    longitude: "REDACTED"
    mode: daily
    name: pirateweather

